owner: sochara-org
repo: status

sites:
  - name: Homepage
    url: https://sochara.org
  - name: Clic
    url: https://clic.sochara.org
  - name: Archives
    url: https://archives.sochara.org
  - name: Archives
    url: https://wiki.sochara.org
  - name: LMS
    url: https://lms.sophea-sochara.org

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sochara Status
  introTitle: "Sochara services status page powered by upptime"
  introMessage: Any issues should be reported to sochara-org/status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
